// <auto-generated />
using System;
using InvestmentOperations.DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentOperations.DataAccess.Migrations
{
    [DbContext(typeof(InvestmentContext))]
    [Migration("20260811110915_RenameBalancesToAssetHoldings")]
    partial class RenameBalancesToAssetHoldings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assetid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assetcode");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assetname");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assettype");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("assets_assetcode_key");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.AssetHolding", b =>
                {
                    b.Property<int>("AssetHoldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assetholdingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssetHoldingId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("assetid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("AssetHoldingId");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId", "AssetId")
                        .IsUnique();

                    b.ToTable("assetholdings", (string)null);
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("logid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("LogId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("logs_ind_01");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("priceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("assetid");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("currentprice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("PriceId");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tradeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TradeId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("assetid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("totalprice");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tradedate");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tradetype");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unitprice");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("TradeId");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("trades_ind_01");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.AssetHolding", b =>
                {
                    b.HasOne("InvestmentOperations.Entities.Concrete.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InvestmentOperations.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.Price", b =>
                {
                    b.HasOne("InvestmentOperations.Entities.Concrete.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_prices_assets");
                });

            modelBuilder.Entity("InvestmentOperations.Entities.Concrete.Trade", b =>
                {
                    b.HasOne("InvestmentOperations.Entities.Concrete.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_trades_assets");

                    b.HasOne("InvestmentOperations.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_trades_users");
                });
#pragma warning restore 612, 618
        }
    }
}
